vault-address: http://localhost:8200
common-name: vault-pki.example.com
vault-pki-role: my_role
vault-mount-pki: pki_intermediate
vault-mount-approle: approle
vault-token: vault-pki-cli
daemonize: true
ttl: 48h
storage:
  - key: file:///tmp/pki.key
    cert: file:///tmp/cert.crt
    aca: file:///tmp/ca.crt
