apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: vault-pki-cli
build:
  artifacts:
  - image: vault-pki-cli
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - assets/k8s/deployment.yaml
