apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-pki-cli-config
data:
  config.yaml: |
    vault_address: http://vault:8200
    common_name: vault-pki.example.com
    vault_pki_role: my_role
    vault_mount_pki: pki_intermediate
    vault_mount_approle: approle
    vault_token: vault-pki-cli
    ttl: 48h
    lifetime-threshold-percent: 66
    storage:
      - key: k8s-sec:///default/key
        cert: k8s-cm:///default/cert
        ca: k8s-cm:///default/ca
