apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-pki-cli
  name: vault-pki-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-pki-cli
  strategy: {}
  template:
    metadata:
      labels:
        app: vault-pki-cli
    spec:
      containers:
        - image: ghcr.io/soerenschneider/vault-pki-cli:9d5b45befb185c0853ed9ac777579d9872de3cbf0db9930abe1493a1126ce581
          name: vault-pki-cli
          command:
            - /vault-pki-cli
            - --config
            - /etc/vault-pki-cli/config.yaml
            - issue
          imagePullPolicy:  IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /etc/vault-pki-cli
      volumes:
        - name: config
          configMap:
            name: vault-pki-cli-config
