---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-pki-cli
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vault-pki-cli
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-pki-cli
subjects:
  - kind: ServiceAccount
    name: vault-pki-cli
roleRef:
  kind: Role  # this must be Role or ClusterRole
  name: vault-pki-cli
  apiGroup: rbac.authorization.k8s.io

